country_list = ['russia', 'ukrain', 'moldova', 'ruminia', 'slovenya']
print('Выводим список стран, в которых я был(почти всех), в исходном виде:\n', country_list)
print('А теперь выводим временно отсортированный по алфавиту список функцией sorted()\n', sorted(country_list))
print('Но при этом список находится в исходном виде:\n', country_list)
print('А теперь выводим отсортированный список в алфавитном порядке, но наоборот функцией sorted(...,reverse = True)\n', sorted(country_list, reverse = True))
print('Но при этом список всё ещё находится в исходном виде:\n', country_list)
country_list.reverse()
print('Выводим список в обратном порядке функцией reverse(). В этом случае список изменился:\n', country_list)
country_list.reverse()
print('Возвращаем список в первоначальном виде той же функцией reverse():\n', country_list)
country_list.sort()
print('Выводим список после постоянной сортировки функицией sort():\n', country_list)
country_list.sort(reverse=True)
print('Сортируем в обратном порядке sort(reverse=True):\n', country_list)
print(len(country_list))